version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  web:
    image: authserver
    build: .
    volumes:
      - .:/app
    command: "npm start"
    ports:
      - 4000:4000
    depends_on:
      - "mongo"
